# Generated by Django 4.2.9 on 2024-01-17 23:15

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('Blogger', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='BlogModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('blog_title', models.CharField(max_length=100, verbose_name='blog title')),
                ('blog_content', models.CharField(max_length=255, verbose_name='blog content')),
                ('blog_creator', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('blog_image', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Blogger.imagemodel')),
            ],
        ),
    ]
