# Generated by Django 4.2.9 on 2024-01-18 00:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Blogger', '0002_blogmodel'),
    ]

    operations = [
        migrations.AlterField(
            model_name='blogmodel',
            name='blog_content',
            field=models.TextField(verbose_name='blog content'),
        ),
    ]
