# Generated by Django 4.2.9 on 2024-01-17 22:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userbloggermodel',
            name='cv',
            field=models.FileField(blank=True, null=True, upload_to=''),
        ),
    ]
